// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "@prisma/config";
import "dotenv/config";

export default defineConfig({
  schema: "prisma/schema.prisma", // Path to your schema file
  datasource: {
    url: env("DATABASE_URL"),     // This replaces the line we deleted
  },
  migrations: {
    seed: 'tsx ./prisma/seed.ts', // 🚨 Add this line
  },
});